/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;
import libraries.pdf.PaymentReceipt;
import models.M_send_payment;

/**
 *
 * @author umarmukhtar
 */
public class ConfirmReceipt extends javax.swing.JFrame {

    public static String cr_card_id = "";
    public static int cr_me_id_from = 0;
    public static int cr_me_id_to = 0;
    public static int cr_pt_id = 0;
    public static int cr_at_id = 0;
    public static double cr_tr_amount = 0.00;
    private static String cr_pin_code = "";
    public static String cr_notes = "";
    
    /**
     * Creates new form ConfirmReceipt
     */
    public ConfirmReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_customer = new javax.swing.JLabel();
        lbl_merchant = new javax.swing.JLabel();
        lbl_amount = new javax.swing.JLabel();
        lbl_pt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pwd_pincode = new javax.swing.JPasswordField();
        lbl_notes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmation Receipt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("<html><center>DinarPal's Debit Gram<br />Confirmation Receipt</center></html>");

        jLabel1.setText("Customer : ");

        jLabel2.setText("Merchant : ");

        jLabel4.setText("Amount Transfer : ");

        jLabel5.setText("Payment Type : ");

        jLabel6.setText("Pin Code : ");

        lbl_customer.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_customer.setText("Umar Mukhtar bin Ham ...");

        lbl_merchant.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_merchant.setText("Nur Umira binti Must ...");

        lbl_amount.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_amount.setText("DPS 0.2 gram");

        lbl_pt.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_pt.setText("Goods");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pwd_pincode.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pwd_pincode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwd_pincodeKeyReleased(evt);
            }
        });

        lbl_notes.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_notes.setText("Trans notes ..");

        jLabel7.setText("Notes : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addComponent(lbl_notes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_merchant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_pt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pwd_pincode))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbl_customer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_merchant))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_amount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_pt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwd_pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
//        String test = "cr_card_id: " + cr_card_id + "\n";
//        test += "cr_me_id_from: " + cr_me_id_from + "\n";
//        test += "cr_me_id_to: " + cr_me_id_to + "\n";
//        test += "cr_pt_id: " + cr_pt_id + "\n";
//        test += "cr_at_id: " + cr_at_id + "\n";
//        test += "cr_tr_amount: " + cr_tr_amount + "\n";
//        test += "cr_pin_code: " + cr_pin_code + "\n";
//        test += "cr_notes: " + cr_notes + "\n";
//        JOptionPane.showMessageDialog(null, test, "Test", 1);
        
        M_send_payment msp = new M_send_payment();
        String[] str_out = msp.sendPaymentDpgdps(cr_card_id, cr_pin_code, cr_me_id_from, cr_me_id_to, cr_tr_amount, cr_at_id, cr_pt_id, cr_notes);
        
        boolean isSend = str_out[0].equals("-1");
        String err_msg = str_out[1];
        
        if (isSend) {
            JOptionPane.showMessageDialog(null, "Payment success.", "Debit Gram Payment", JOptionPane.INFORMATION_MESSAGE);
            PaparanTerminal.clearField();
            
            // generate pdf receipt
            int tr_id = 0;
            try {
                tr_id = Integer.parseInt(str_out[1]);
            } catch (Exception e) {
                tr_id = 0;
            }
            PaymentReceipt pr = new PaymentReceipt("Payment_Receipt");
            pr.generate(1, tr_id);
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Payment failed!\n"+err_msg, "Debit Gram Payment", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pwd_pincodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwd_pincodeKeyReleased
        // TODO add your handling code here:
        char p[] = pwd_pincode.getPassword();
        String pc = "";
        for (int i = 0; i < p.length; i++) {
            pc += p[i];
        }
        this.cr_pin_code = pc;
    }//GEN-LAST:event_pwd_pincodeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbl_amount;
    public static javax.swing.JLabel lbl_customer;
    public static javax.swing.JLabel lbl_merchant;
    public static javax.swing.JLabel lbl_notes;
    public static javax.swing.JLabel lbl_pt;
    public static javax.swing.JPasswordField pwd_pincode;
    // End of variables declaration//GEN-END:variables
}
